apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z7hv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-z7hv@sha256:a9e9933a2c77aba167624ca9f6dac23291713c4f2d0b1399766600eafd460b34
        name: my-nodejs
        resources: {}
status: {}
